"""Add total_questions and total_duration to InterviewSession

Revision ID: 05b380c1ae05
Revises: 2cb1ff248b70
Create Date: 2025-07-08 19:24:35.376994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05b380c1ae05'
down_revision = '2cb1ff248b70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interview_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_questions', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_duration', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interview_sessions', schema=None) as batch_op:
        batch_op.drop_column('total_duration')
        batch_op.drop_column('total_questions')

    # ### end Alembic commands ###
