"""Fix ChatLog table and foreign key

Revision ID: 2cb1ff248b70
Revises: aeaa1562ca5d
Create Date: 2025-07-08 18:37:32.649580

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2cb1ff248b70'
down_revision = 'aeaa1562ca5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('question', sa.Text(), nullable=True),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('chat_logs')
    with op.batch_alter_table('resume_score', schema=None) as batch_op:
        batch_op.alter_column('candidate_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resume_score', schema=None) as batch_op:
        batch_op.alter_column('candidate_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    op.create_table('chat_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sender', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], name=op.f('chat_logs_session_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('chat_logs_pkey'))
    )
    op.drop_table('chat_log')
    # ### end Alembic commands ###
