"""Fix ResumeScore foreign key

Revision ID: b4e5efdb1f56
Revises: 
Create Date: 2025-07-08 16:26:32.487272

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b4e5efdb1f56'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('interview')
    # op.drop_table('candidate')
    with op.batch_alter_table('resume_score', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('resume_score_candidate_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'candidates', ['candidate_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resume_score', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('resume_score_candidate_id_fkey'), 'candidate', ['candidate_id'], ['id'])

    op.create_table('candidate',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('candidate_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('cv_file_path', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('total_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='candidate_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('interview',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('candidate_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('interview_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('start_time', postgresql.TIME(), autoincrement=False, nullable=False),
    sa.Column('end_time', postgresql.TIME(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate.id'], name=op.f('interview_candidate_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('interview_pkey'))
    )
    # ### end Alembic commands ###
